version: "3"

services:
  redis-replica-acl-srv:
    build: .
    image: redis-replica-acl-srv-img
    container_name: redis-replica-acl-srv
    restart: "no"
    ports:
      - "127.0.0.1:63790:6379"
    networks:
      - redis-net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  redis-net:
    external: true
